### ISSUE TITLE
coverage tests are actually coverage + functional tests

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/sample_app#79] opened 2020-06-24 14:39 UTC
**Is your feature request related to a problem? Please describe.**
The current "coverage" tests are much like the unit tests in other cFS repositories, where stubs are configured to cause errors and the return values and events are checked. This is, in my opinion, intermixing functional and coverage testing. Changing the type of event generated for an error condition will not affect coverage, but will require changing the unit test code which would fail, given that it was expecting the previous error condition.

For example, instead of:
```
UT_SetDeferredRetcode(UT_KEY(CFE_SB_Subscribe), 2, CFE_SB_BAD_ARGUMENT);
UT_TEST_FUNCTION_RC(SAMPLE_AppInit(), CFE_SB_BAD_ARGUMENT);
UtAssert_True(UT_GetStubCount(UT_KEY(CFE_ES_WriteToSysLog)) == 4, "CFE_ES_WriteToSysLog() called");
```

it could be written more simply as:
```
UT_SetDeferredRetcode(UT_KEY(CFE_SB_Subscribe), 2, CFE_SB_BAD_ARGUMENT);
SAMPLE_AppInit();
```

No need to check return or events.

**Describe alternatives you've considered**
One option would be to keep it as it is, but I suggest renaming it back to (more ambiguous) unit tests. Or split the code into true coverage tests (which would exercise every path) and functional tests (which would focus on nominal operation and significant error handling).

**Requester Info**
Christopher.D.Knight@nasa.gov

**Comment by skliper** [comment] 2020-06-25 11:40
Many event messages can only be checked with mocks and stubs, and it's a requirement to verify them all.  The unit being coverage tested does need to be checked in terms of did it do what it was supposed to based on the path chosen.  It's not full stack functional, but there is an aspect of making sure the code under test does what it is supposed to (especially error responses).  If there's a new name we want to make up for this sort of test (mocks and stubs, full coverage, verifies code behaves correctly based on path taken) I'm fine with that, but please don't remove the checks.

What we don't need in these tests is anything that checks the functions called by the unit under test (since they are likely stubbed out anyways).

**Comment by CDKnightNASA** [comment] 2020-06-25 13:27
Ok, just noting that it makes coverage testing more complex and more inter-dependent with the code its testing (change the events, the messages, or return value and you have to change the coverage test code to match.)

**Comment by jphickey** [comment] 2020-06-25 13:27
Coverage and functionality tests inherently both do coverage and functionality to some degree.  They just have different primary focus depending on the test environment/goals.

The primary goal of this test is coverage.  Any functionality that may be tested is limited direct, locally produced outputs of the function under test, given the preconditions set up in the test case.  That is, it should check only things that are computed entirely within the unit being tested and are not dependent on external libraries.  

A return code is an example of something I _do_ recommend checking for two reasons
- It is generally computed locally within the unit under test (i.e. value is not dependent on output of external library call like snprintf or something)
- It confirms that the intended path was followed (i.e. that the error path that the test case was intended to execute was actually executed, not some other error path)

What coverage test should _NOT_ check are derived outputs, such as:
- The bits/values inside a `CFE_SB_Msg_t` structure after calling Message accessor getter/setter functions - this depends on the implementation of those accessors, and they will be stubs.  The test may validate that these were called but it cannot validate the effect of that call (UNLESS it installs a hook function to force its own effect).
- The complete/formatted message string produced by `CFE_EVS_SendEvent()` - as this depends on the implementation of CFE_EVS_SendEvent, which is a stub and not part of the unit under test.  The test may validate all the parameters with which the unit invoked CFE_EVS_SendEvent (the event ID, type, format string, and variable parameters) as these are directly produced by the unit.  But the final string is a derived output.

**Closed** 2020-06-25 13:27 UTC
